=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/dataset-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://digitalhps.org/lerna-Dataset-model" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://digitalhps.org/lerna-Dataset-model">

    <xsd:element name="dataset">
    	<xsd:complexType>
    		<xsd:sequence>
    			<xsd:element name="datasetType" type="xsd:string"></xsd:element>
                <xsd:element name="indexRelation" type="xsd:boolean"></xsd:element>
                <xsd:element name="databaseList" type="DatabaseList"
    				maxOccurs="1" minOccurs="0">
    			</xsd:element>
    			<xsd:element name="nodeList" maxOccurs="1" minOccurs="0"
    				type="NodeList">
    			</xsd:element>
    			<xsd:element name="relationList" maxOccurs="1"
    				minOccurs="0" type="RelationList">
    			</xsd:element>
    		</xsd:sequence>
    	</xsd:complexType>
    </xsd:element>

    


    <xsd:element name="NodeList" type="NodeList"></xsd:element>
    
    <xsd:element name="RelationList" type="RelationList"></xsd:element>
    
    <xsd:complexType name="NodeList">
    	<xsd:sequence>
    		<xsd:element name="node" maxOccurs="unbounded" minOccurs="1">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="id" type="xsd:long"
    						maxOccurs="1" minOccurs="1">
    					</xsd:element>
    					<xsd:element name="label"
    						type="xsd:string" maxOccurs="1" minOccurs="1">
    					</xsd:element>
    					<xsd:element name="propertyList"
    						type="PropertyList" maxOccurs="1" minOccurs="0">
    					</xsd:element>
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RelationList">
    	<xsd:sequence>
    		<xsd:element name="relation" maxOccurs="unbounded" minOccurs="0">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="id" type="xsd:long" maxOccurs="1" minOccurs="1"></xsd:element>
    					<xsd:element name="type"
    						type="xsd:string" maxOccurs="1" minOccurs="1">
    					</xsd:element>
    					<xsd:element name="propertyList"
    						type="PropertyList" maxOccurs="1" minOccurs="0">
    					</xsd:element>
    					<xsd:element name="startNode" type="xsd:long" maxOccurs="1" minOccurs="1"></xsd:element>
    					<xsd:element name="endNode" type="xsd:long" maxOccurs="1" minOccurs="1"></xsd:element>
    				</xsd:sequence>
    			</xsd:complexType></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>



    <xsd:element name="PropertyList" type="PropertyList"></xsd:element>
    
    <xsd:complexType name="PropertyList">
    	<xsd:sequence>
    		<xsd:element name="property" maxOccurs="unbounded" minOccurs="0">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="name" type="xsd:string" maxOccurs="1" minOccurs="1">
    					</xsd:element>
    					<xsd:element name="value"
    						type="xsd:string" maxOccurs="1" minOccurs="1">
    					</xsd:element>
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    

    <xsd:complexType name="DatabaseList">
    	<xsd:sequence>
    		<xsd:element name="database" maxOccurs="unbounded" minOccurs="0" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Property">
    	<xsd:complexType></xsd:complexType>
    </xsd:element>

    <xsd:element name="database">
    	<xsd:complexType></xsd:complexType>
    </xsd:element>

    <xsd:element name="Node">
    	<xsd:complexType></xsd:complexType>
    </xsd:element>

    <xsd:element name="Relation">
    	<xsd:complexType></xsd:complexType>
    </xsd:element>

    <xsd:element name="DatabaseList" type="DatabaseList"></xsd:element>
</xsd:schema>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/test/resources/sampleDataset.xml
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://digitalhps.org/lerna-Dataset-model" xsi:schemaLocation="http://digitalhps.org/lerna-Dataset-model dataset-schema.xsd">
	<datasetType>kk</datasetType>
	<databaseList>
		<database>1</database>
		<database>20</database>
	</databaseList>
	<nodeList>
		<node>
			<id>1</id>
			<label>Person</label>
			<propertyList>
				<property>
					<name>Name</name>
					<value>Karan</value>
				</property>
			</propertyList>
		</node>
		<node>
			<id>2</id>
			<label>Institute</label>
			<propertyList>
				<property>
					<name>University</name>
					<value>ASU</value>
				</property>
			</propertyList>
		</node>
	</nodeList>
	<relationList>
		<relation>
			<id>1</id>
			<type>affiliatedWith</type>
			<propertyList>
				<property>
					<name>Year</name>
					<value>2013</value>
				</property>
			</propertyList>
			<startNode>1</startNode>
			<endNode>2</endNode>
		</relation>
	</relationList>
</dataset>
