=== jdamerow/Iolaus/trunk/lerna-iolaus/src/test/resources/query-schema.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns="http://digitalhps.org/lerna-query-model" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://digitalhps.org/lerna-query-model" elementFormDefault="qualified">

    <xs:element name="query">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="databaseList" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="dataset" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="node" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="relationship" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="database">
        <xs:complexType>
        	<xs:simpleContent>
        		<xs:extension base="xs:string"></xs:extension>
        	</xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="dataset">
        <xs:complexType>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="property">
        <xs:complexType>
        	<xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="type" type="xs:string"/>
            <xs:attribute name="value" type="xs:string"/>
            <xs:attribute name="start" type="xs:integer"/>
            <xs:attribute name="end" type="xs:integer"/>            
        </xs:complexType>
    </xs:element>

    <xs:element name="node">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="property" minOccurs="0"/>
                <xs:element ref="relationship" minOccurs="0"/>
                <xs:element ref="and" minOccurs="0"/>
                <xs:element ref="or" minOccurs="0"/>
            </xs:choice>
            <xs:attribute name="return" type="xs:boolean" />
            <xs:attribute name="id" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="relationship">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="source" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="target" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="property" minOccurs="0"/>
                <xs:element ref="and" minOccurs="0"/>
                <xs:element ref="or" minOccurs="0"/>
            </xs:choice>
            <xs:attribute name="return" type="xs:boolean" />
            <xs:attribute name="id" type="xs:string" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="source" type="rel_node"/>
    <xs:element name="target" type="rel_node"/>
    
    <xs:complexType name="rel_node">
        <xs:sequence>
            <xs:element ref="node"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="and" type="operator"/>
    <xs:element name="or" type="operator"/>

    <xs:complexType name="operator">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="source" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="target" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="property" minOccurs="0"/>
            <xs:element ref="relationship" minOccurs="0"/>
            <xs:element ref="and" minOccurs="0"/>
            <xs:element ref="or" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="databaseList">
    	<xs:sequence>
    		<xs:element ref="database" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:element name="databaseList" type="databaseList"></xs:element>
</xs:schema>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/SampleInput3.xml
<!--What was the role of person [A] in course [X] in year [Y]?-->
<query 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns="http://digitalhps.org/lerna-query-model" 
		xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
    <databaseList>
		<database>1</database>
	</databaseList>
    <dataset id = "mblcourses" />
    <node return="true">
        <and>
            <property name="type" value="Person" />              
            <relationship return="true">
                <property name="type" value="attended" />
                <property name="year" value="1900" />
                    <target>
                        <node>
							<property name="type" value="Series"/>
							<property name="label" value="Zoolo" /> 
                        </node>
                    </target>
            </relationship>
        </and>
    </node>      
</query>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/SampleInput2.xml
<!-- What courses did person [A] attend? (between years [Y] and [Z]?) -->
<query 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns="http://digitalhps.org/lerna-query-model" 
		xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
    <databaseList>
		<database>1</database>
	</databaseList>
    <dataset id = "mblcourses" />
    <node return="true">
        <and>
            <property name="type" value="Course" />              
            <relationship return="true" type="attended">
                <property name="year" type="range" start="1800" end="1920" />
                    <source>
                        <node>
	    		    		<property name="lastname" value="Setchell" /> 
                        </node>
                    </source>
            </relationship>
        </and>
    </node>      
</query>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/SampleInput8.xml
<!--What are the Locations of Person who attended Course[C] in year[1920] ?-->
<query xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://digitalhps.org/lerna-query-model" xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
	<databaseList>
		<database>1</database>
	</databaseList>
	<dataset id="mblcourses" />
	<node return="true">
		<and>
			<property name="type" value="Location" />
			<relationship return="true" type="hasLocation">
				<source>
					<node return="true">
						<and>
							<property name="type" value="Person" />
							<relationship return="false" type="attended">
								<property name="year" value="1920"/>
								<target>
									<node return="true">
										<property name="type" value="Course" />
										<property name="name" value="Botany" />
									</node>
								</target>
							</relationship>
						</and>
					</node>
				</source>
			</relationship>
		</and>
	</node>
</query>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/SampleInput6.xml
<!--Who was affiliated with institution [I]? (between years [Y] and [Z]?)-->
<query 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns="http://digitalhps.org/lerna-query-model" 
		xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
    <databaseList>
		<database>1</database>
	</databaseList>
    <dataset id = "mblcourses" />
    <node return="true">
        <and>
            <property name="type" value="Person" />   
            <relationship return="true" type="hasAffiliation">
                <property name="year" type="range" start="1900" end="1920" />
                    <target>
                        <node>
                            <property name="type" value="Institution" />
                            <property name="name" value="Harvard" />
                        </node>
                    </target>
            </relationship>
        </and>
    </node>      
</query>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/SampleInput5.xml
<!--What courses did people from institution [I] attend? -->
<query xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://digitalhps.org/lerna-query-model" xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
	<databaseList>
		<database>1</database>
	</databaseList>
	<dataset id="mblcourses" />
	<node return="true">
		<and>
			<property name="type" value="Course" />
			<relationship return="true" type="attended">
			<property name="year" start="1900"/>
				<source>
					<node return="true">
						<and>
							<property name="type" value="Person" />
							<relationship return="true" type="hasAffiliation">
								<target>
									<node return="true">
										<property name="type" value="Institution" />
										<property name="name" value="Harvard" />
									</node>
								</target>
							</relationship>
						</and>
					</node>
				</source>
			</relationship>
		</and>
	</node>
</query>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/SampleInput4.xml
<!--Who held role [B] in course [X]?-->
<query 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns="http://digitalhps.org/lerna-query-model" 
		xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
    <database id="2"/>
    <dataset id = "mblcourses" />
    <node return="true">
        <and>
            <property name="type" value="Person" />              
            <relationship return="true">
                <property name="type" value="attended" />
                <property name="role" value="Instructor" />
                    <target>
                        <node>
							<property name="type" value="Series"/>
							<property name="label" value="Zool" /> 
                        </node>
                    </target>
            </relationship>
        </and>
    </node>      
</query>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/SampleInput7.xml
<!--Where was Person [P] located?-->
<query 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns="http://digitalhps.org/lerna-query-model" 
		xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
    <databaseList>
		<database>1</database>
	</databaseList>
    <dataset id = "mblcourses" />
    <node return="true">
        <and>
            <property name="type" value="Location" />   
            <relationship return="true" type="hasLocation">
				<source>
					<node>
                        <property name="type" value="Person" />
                        <property name="lastname" value="Setchell" />
                    </node>
                </source>
            </relationship>
        </and>
    </node>      
</query>

=== jdamerow/Iolaus/trunk/lerna-iolaus/src/main/resources/getNode_nodes.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<query 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xmlns="http://digitalhps.org/lerna-query-model" 
		xsi:schemaLocation="http://digitalhps.org/lerna-query-model query-schema.xsd">
    <database id="2"/>
    <dataset id = "mblcourses" />
    <node return="true">
        <and>
            <property name="type" value="Person" />        
            <relationship return="true">
                <property name="type" value="hasLocation" />
                <property name="date" type="range" start="1900" end="1920" />
                <or>
                    <target>
                        <node>
                            <property name="type" value="Location" />
                            <property name="city" value="Alberta" />
                        </node>
                    </target>
                    <target>
                        <node>
                            <property name="type" value="Location" />
                            <property name="city" value="Yonkers" />
                        </node>
                    </target>
                </or>
            </relationship>
        </and>
    </node>      
</query>
